config/routes.rb
Rails.application.routes.draw do
  resources :characters
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/character.rb
class Character < ApplicationRecord

  def attributes_name_and_age
    m = []
    m.push(self.name, self.age)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/characters_controller.rb
class CharactersController < ApplicationController
  before_action :set_character, only: [:show, :edit, :update, :destroy]

  # GET /characters
  # GET /characters.json
  def index
    @characters = Character.all
  end

  # GET /characters/1
  # GET /characters/1.json
  def show
  end

  # GET /characters/new
  def new
    @character = Character.new
  end

  # GET /characters/1/edit
  def edit
  end

  # POST /characters
  # POST /characters.json
  def create
    @character = Character.new(character_params)

    respond_to do |format|
      if @character.save
        format.html { redirect_to @character, notice: 'Character was successfully created.' }
        format.json { render :show, status: :created, location: @character }
      else
        format.html { render :new }
        format.json { render json: @character.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /characters/1
  # PATCH/PUT /characters/1.json
  def update
    respond_to do |format|
      if @character.update(character_params)
        format.html { redirect_to @character, notice: 'Character was successfully updated.' }
        format.json { render :show, status: :ok, location: @character }
      else
        format.html { render :edit }
        format.json { render json: @character.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /characters/1
  # DELETE /characters/1.json
  def destroy
    @character.destroy
    respond_to do |format|
      format.html { redirect_to characters_url, notice: 'Character was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_character
      @character = Character.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def character_params
      params.require(:character).permit(:name, :age, :race, :hp, :physical_attack, :physical_defense, :physical_critical_chance, :evasion, :accuracy, :hp_recovery, :chance_block_shield, :cash)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/characters_helper.rb
module CharactersHelper
end

app/views/characters/_form.html.erb
<%= form_with(model: character, local: true) do |form| %>
  <% if character.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(character.errors.count, "error") %> prohibited this character from being saved:</h2>

      <ul>
      <% character.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :character_name %>
  </div>

  <div class="field">
    <%= form.label :age %>
    <%= form.number_field :age, id: :character_age %>
  </div>

  <div class="field">
    <%= form.label :race %>
    <%= form.text_field :race, id: :character_race %>
  </div>

  <div class="field">
    <%= form.label :hp %>
    <%= form.number_field :hp, id: :character_hp %>
  </div>

  <div class="field">
    <%= form.label :physical_attack %>
    <%= form.number_field :physical_attack, id: :character_physical_attack %>
  </div>

  <div class="field">
    <%= form.label :physical_defense %>
    <%= form.number_field :physical_defense, id: :character_physical_defense %>
  </div>

  <div class="field">
    <%= form.label :physical_critical_chance %>
    <%= form.number_field :physical_critical_chance, id: :character_physical_critical_chance %>
  </div>

  <div class="field">
    <%= form.label :evasion %>
    <%= form.number_field :evasion, id: :character_evasion %>
  </div>

  <div class="field">
    <%= form.label :accuracy %>
    <%= form.number_field :accuracy, id: :character_accuracy %>
  </div>

  <div class="field">
    <%= form.label :hp_recovery %>
    <%= form.number_field :hp_recovery, id: :character_hp_recovery %>
  </div>

  <div class="field">
    <%= form.label :chance_block_shield %>
    <%= form.number_field :chance_block_shield, id: :character_chance_block_shield %>
  </div>

  <div class="field">
    <%= form.label :cash %>
    <%= form.text_field :cash, id: :character_cash %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/characters/edit.html.erb
<h1>Editing Character</h1>

<%= render 'form', character: @character %>

<%= link_to 'Show', @character %> |
<%= link_to 'Back', characters_path %>

app/views/characters/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Characters</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Age</th>
      <th>Race</th>
      <th>Hp</th>
      <th>Physical attack</th>
      <th>Physical defense</th>
      <th>Physical critical chance</th>
      <th>Evasion</th>
      <th>Accuracy</th>
      <th>Hp recovery</th>
      <th>Chance block shield</th>
      <th>Cash</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @characters.each do |character| %>
      <tr>
        <td><%= character.name %></td>
        <td><%= character.age %></td>
        <td><%= character.race %></td>
        <td><%= character.hp %></td>
        <td><%= character.physical_attack %></td>
        <td><%= character.physical_defense %></td>
        <td><%= character.physical_critical_chance %></td>
        <td><%= character.evasion %></td>
        <td><%= character.accuracy %></td>
        <td><%= character.hp_recovery %></td>
        <td><%= character.chance_block_shield %></td>
        <td><%= character.cash %></td>
        <td><%= link_to 'Show', character %></td>
        <td><%= link_to 'Edit', edit_character_path(character) %></td>
        <td><%= link_to 'Destroy', character, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Character', new_character_path %>

app/views/characters/new.html.erb
<h1>New Character</h1>

<%= render 'form', character: @character %>

<%= link_to 'Back', characters_path %>

app/views/characters/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @character.name %>
</p>

<p>
  <strong>Age:</strong>
  <%= @character.age %>
</p>

<p>
  <strong>Race:</strong>
  <%= @character.race %>
</p>

<p>
  <strong>Hp:</strong>
  <%= @character.hp %>
</p>

<p>
  <strong>Physical attack:</strong>
  <%= @character.physical_attack %>
</p>

<p>
  <strong>Physical defense:</strong>
  <%= @character.physical_defense %>
</p>

<p>
  <strong>Physical critical chance:</strong>
  <%= @character.physical_critical_chance %>
</p>

<p>
  <strong>Evasion:</strong>
  <%= @character.evasion %>
</p>

<p>
  <strong>Accuracy:</strong>
  <%= @character.accuracy %>
</p>

<p>
  <strong>Hp recovery:</strong>
  <%= @character.hp_recovery %>
</p>

<p>
  <strong>Chance block shield:</strong>
  <%= @character.chance_block_shield %>
</p>

<p>
  <strong>Cash:</strong>
  <%= @character.cash %>
</p>

<%= link_to 'Edit', edit_character_path(@character) %> |
<%= link_to 'Back', characters_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RspecRails</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>